### ISSUE TITLE
配置文件注册路由，无法注册

### ISSUE THREAD

**Issue by justsolove** [we7coreteam/w7-rangine-empty#2]
<?php

return [
	'/' => [
		'method' => 'GET',
		//路由分組name
		'name' => 'route-home',

		//公共的中间件
		'middleware' => [
			\W7\App\Middleware\TestMiddleware::class
		],
		//当该路由的name未定义时，默认name生成方式为分组路由的name按.连接，再拼接上当前路由的action
		'handler' => 'Home\WelcomeController@index', //指定处理方法
	],
    'login' => [
        'method' => 'GET',
        'prefix' => 'login',
        //路由分組name
        'name' => 'route-login',
        //公共的中间件
        'middleware' => [
            \W7\App\Middleware\TestMiddleware::class
        ],
        'index' => [
            'login' => [
                'name' => 'route-name1'
            ],
            'bottom' => [
                'name' => 'route-name2'
            ]

        ],
        'chack' => [
            'login' => [
                'name' => 'route-name3'
            ],
            'bottom' => [
                'name' => 'route-name4'
            ]
        ]

    ],

];``

**Comment by titrxw** [comment]
已修复，可在master分支查看
