### ISSUE TITLE
这个是没人维护了吗？

### ISSUE THREAD

**Issue by jishuXiaom** [we7coreteam/w7-rangine-empty#7]
快以一年没动静了，文档也太。。。

**Comment by titrxw** [comment]
这个是demo空项目，https://github.com/we7coreteam/w7-rangine　这个是对应的框架．
文档哪部分有问题？我们这边更新下．

**Comment by jishuXiaom** [comment]
好的

**Comment by jishuXiaom** [comment]
会把最新的框架同步到demo下面吗？
